version: '3.9'

services: 
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCES_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCES_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

